### ISSUE TITLE
Fix partial merge configuration file

### ISSUE THREAD

**Issue by rolfsimoes** [e-sensing/sits#367]
SITS_CONFIG_USER_FILE can point to a user file that modifies default sits configuration.
Current version of `sits` does not allow partial change of sits configuration.
For example, the following exerpt:
```yml
sources:
    BDC:
        url: http://example.com/
```
should change `url` key value for `BDC` cube.
